Repository muizzyusuf/ethics-dashboard-2, pull requests merged in 2021-11, with the labels that each got.

#46 Course select/create
  ethicsdashboard/app/Http/Controllers/Auth/RegisterController.php
  ethicsdashboard/app/Http/Controllers/CaseStudyController.php
  ethicsdashboard/app/Http/Controllers/CourseController.php
  ethicsdashboard/app/Http/Controllers/HomeController.php
  ethicsdashboard/app/Models/Course.php
  ethicsdashboard/app/Models/CourseUser.php
  ethicsdashboard/app/Models/User.php
  ethicsdashboard/composer.lock
  ethicsdashboard/database/migrations/2014_10_12_000000_create_users_table.php
  ethicsdashboard/database/migrations/2021_11_03_175315_create_ethical_issues_table.php
  ethicsdashboard/database/migrations/2021_11_03_175736_create_stakeholder_sections_table.php
  ethicsdashboard/database/migrations/2021_11_03_175823_create_utilitarianism_sections_table.php
  ethicsdashboard/database/seeders/DatabaseSeeder.php
  ethicsdashboard/resources/views/auth/register.blade.php
  ethicsdashboard/resources/views/casestudy.blade.php
  ethicsdashboard/resources/views/courseCreate.blade.php
  ethicsdashboard/resources/views/home.blade.php
  ethicsdashboard/resources/views/layouts/app.blade.php
  ethicsdashboard/resources/views/partials/alerts.blade.php
  ethicsdashboard/routes/web.php
Labels: task

#47 Update RegisterController.php
  ethicsdashboard/app/Http/Controllers/Auth/RegisterController.php
Labels: bug

#55 Register students
  ethicsdashboard/app/Http/Controllers/CaseStudyController.php
  ethicsdashboard/app/Http/Controllers/CourseController.php
  ethicsdashboard/app/Http/Controllers/CourseUserController.php
  ethicsdashboard/app/Http/Controllers/HomeController.php
  ethicsdashboard/app/Models/User.php
  ethicsdashboard/database/seeders/DatabaseSeeder.php
  ethicsdashboard/database/seeders/RoleSeeder.php
  ethicsdashboard/database/seeders/UserSeeder.php
  ethicsdashboard/resources/views/auth/register.blade.php
  ethicsdashboard/resources/views/casestudy.blade.php
  ethicsdashboard/resources/views/course.blade.php
  ethicsdashboard/resources/views/grade.blade.php
  ethicsdashboard/resources/views/people.blade.php
  ethicsdashboard/resources/views/student/casestudy.blade.php
  ethicsdashboard/resources/views/student/course.blade.php
  ethicsdashboard/resources/views/student/dashboard.blade.php
  ethicsdashboard/resources/views/student/grade.blade.php
  ethicsdashboard/resources/views/student/home.blade.php
  ethicsdashboard/resources/views/student/people.blade.php
  ethicsdashboard/resources/views/welcome.blade.php
  ethicsdashboard/routes/web.php
Labels: task

#78 Utilitarianism section milestone1
  ethicsdashboard/app/Http/Controllers/ConsequenceController.php
  ethicsdashboard/app/Http/Controllers/DashboardController.php
  ethicsdashboard/app/Http/Controllers/EthicalIssueController.php
  ethicsdashboard/app/Http/Controllers/ImpactController.php
  ethicsdashboard/app/Http/Controllers/PleasureController.php
  ethicsdashboard/app/Http/Controllers/ProgressController.php
  ethicsdashboard/app/Http/Controllers/StakeholderSectionController.php
  ethicsdashboard/app/Http/Controllers/UtilitarianismSectionController.php
  ethicsdashboard/app/Models/Consequence.php
  ethicsdashboard/app/Models/Impact.php
  ethicsdashboard/app/Models/Option.php
  ethicsdashboard/app/Models/Pleasure.php
  ethicsdashboard/app/Models/Stakeholder.php
  ethicsdashboard/database/migrations/2021_11_03_175823_create_utilitarianism_sections_table.php
  ethicsdashboard/resources/views/aggregate.blade.php
  ethicsdashboard/resources/views/dashboard.blade.php
  ethicsdashboard/resources/views/ethicalissue.blade.php
  ethicsdashboard/resources/views/impact.blade.php
  ethicsdashboard/resources/views/progress.blade.php
  ethicsdashboard/resources/views/stakeholder.blade.php
  ethicsdashboard/resources/views/student/aggregate.blade.php
  ethicsdashboard/resources/views/student/ethicalissue.blade.php
  ethicsdashboard/resources/views/student/impact.blade.php
  ethicsdashboard/resources/views/student/stakeholder.blade.php
  ethicsdashboard/resources/views/student/summary.blade.php
  ethicsdashboard/resources/views/student/utilitarianism.blade.php
  ethicsdashboard/resources/views/summary.blade.php
  ethicsdashboard/resources/views/utilitarianism.blade.php
  ethicsdashboard/routes/web.php
Labels: chore, task, exploration

#79 low bug fixed on utilitarianism summary
  ethicsdashboard/resources/views/student/summary.blade.php
  ethicsdashboard/resources/views/summary.blade.php
Labels: chore

#77 Update welcome.blade.php
  ethicsdashboard/resources/views/welcome.blade.php
Labels: chore, task, exploration
